lint and check, cleanup idiomatic go issues
Layr-Labs/sidecar pull request #48
Opened 2024-09-13 19:28 UTC by jac18281828

This cleans up many issues with idiomatic go, it also adds a requirement that these checks are enabled in the continuous build

2024-09-13 19:58 UTC, seanmcgary requested changes

2024-09-13 19:58 UTC, seanmcgary commented on Makefile
> +lint:
@jac18281828 you may need to update from master. I added similar targets for lint and formatting yesterday

https://github.com/Layr-Labs/go-sidecar/blob/master/Makefile#L63-L71

2024-09-13 19:58 UTC, seanmcgary commented on Makefile
> +ci-test: test lint vet fmtcheck yamlfmt
Suggest leaving these as all separate; that way we can run individual github actions for them to clearly show which is failing (also means they can run in parallel)

2024-09-13 19:58 UTC, seanmcgary commented on internal/eigenState/stateManager/stateManager_test.go
> +	teardown(NewEigenStateManager(l, grm))
Rather than taking a new instance of the struct, `teardown()` should probably just take a `*gorm.DB` pointer since in this context it's used to delete contents from the table used in the tests.

2024-09-13 19:58 UTC, seanmcgary commented on internal/eigenState/stateManager/stateManager_test.go
> +	teardown(NewEigenStateManager(l, grm))
```go
func teardown(grm *gorm.DB) {
    grm.Exec("delete from state_roots")
}

2024-09-14 15:33 UTC, jac18281828 commented on .golangci.yml
> -
The linters below are not passing and will require some refactor to get them passing.  I backed it out to a basic setup so the ci-cd will be passing for now.    We need to take a look at the functions that have high complexity and make sure we are following the best practices there.

2024-09-14 15:37 UTC, jac18281828 commented on Makefile
> +lint:
Okay I have merged those changes.  I'd ask that we start to use approved pull requests as the way to merge so that we can all stay current on what changes are happening.

2024-09-14 15:38 UTC, jac18281828 commented on Makefile
> +ci-test: test lint vet fmtcheck yamlfmt
yeah we can split that out into separate actions, they are run individually in the test section above.  That is probably sufficient.   This line is the dependency requirement to build the image so they all should be here.

2024-09-14 15:39 UTC, jac18281828 commented on internal/eigenState/stateManager/stateManager_test.go
> +	teardown(NewEigenStateManager(l, grm))
✅

2024-09-16 13:46 UTC, seanmcgary commented on .golangci.yml
> -
Ok sounds good! I knew they were a bit aggressive which was why I hadnt enforced it in CI yet, but backing it out is fine to get it running.

2024-09-16 13:48 UTC, seanmcgary approved these changes

2024-09-16 13:48 UTC, merged